services:
  flights-service:
    build: !reset null
    image: ghcr.io/acostaf12/ctv-flights-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod

  backend:
    build: !reset null
    image: ghcr.io/acostaf12/ctv-backend:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CORS_ALLOWED_ORIGIN_PATTERNS: ${CORS_ALLOWED_ORIGIN_PATTERNS:-http://localhost:*,http://127.0.0.1:*}

  frontend:
    build: !reset null
    image: ghcr.io/acostaf12/ctv-frontend:latest
