CREATE TABLE agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL
);

CREATE TABLE cities (
    code VARCHAR(3) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_type VARCHAR(31) NOT NULL,
    username VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    agency_id BIGINT REFERENCES agencies(id)
);

CREATE TABLE hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    city_code VARCHAR(3) NOT NULL REFERENCES cities(code),
    photo_url VARCHAR(500) NOT NULL
);

CREATE TABLE packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL REFERENCES agencies(id),
    hotel_id BIGINT NOT NULL REFERENCES hotels(id),
    origin_city_code VARCHAR(3) NOT NULL REFERENCES cities(code),
    destination_city_code VARCHAR(3) NOT NULL REFERENCES cities(code),
    name VARCHAR(160) NOT NULL,
    outbound_flight_id BIGINT NOT NULL,
    return_flight_id BIGINT NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT uk_packages_agency_name UNIQUE (agency_id, name)
);

CREATE TABLE purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL REFERENCES users(id),
    package_id BIGINT NOT NULL REFERENCES packages(id),
    agency_id BIGINT NOT NULL REFERENCES agencies(id),
    purchase_price NUMERIC(12, 2) NOT NULL,
    purchased_at TIMESTAMP NOT NULL
);

CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL REFERENCES users(id),
    package_id BIGINT NOT NULL REFERENCES packages(id),
    CONSTRAINT uk_favorites_buyer_package UNIQUE (buyer_id, package_id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL REFERENCES users(id),
    package_id BIGINT NOT NULL REFERENCES packages(id),
    score INTEGER NOT NULL,
    comment TEXT,
    CONSTRAINT uk_reviews_buyer_package UNIQUE (buyer_id, package_id)
);
