# Application

spring.application.name=flights-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:8081}

# Traces

management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:1.0}
management.tracing.export.zipkin.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# Actuator

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
